name = "robinhood-detective"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "BOT_STATE"
id = "a5cd447820754ae3845354059a79fa6a"

[triggers]
crons = ["*/3 * * * *"]

[vars]
DRY_RUN = "false"

[observability]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1